import { useState } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight, Brain, RotateCcw, Sparkles } from "lucide-react";
import { api } from "../api/axios";

type Q={question:string;options:string[];correctAnswer:number;explanation?:string};
export default function Quizzes(){
 const [subject,setSubject]=useState("Computer Science"),[topic,setTopic]=useState("Data Structures"),[difficulty,setDifficulty]=useState("medium"),[count,setCount]=useState(5);
 const [quiz,setQuiz]=useState<any>(null),[current,setCurrent]=useState(0),[answers,setAnswers]=useState<Record<number,number>>({}),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function generate(){setLoading(true);setError("");try{const r=await api.post("/quizzes/generate",{subject,topic,difficulty,numQuestions:count});setQuiz(r.data.data);setCurrent(0);setAnswers({});}catch(e:any){setError(e.response?.data?.message||"Quiz generation failed. Check your AI/API configuration.");}finally{setLoading(false);}}
 const questions:Q[]=quiz?.questions||[]; const q=questions[current]; const finished=questions.length>0&&current===questions.length;
 if(finished){const score=questions.reduce((n,x,i)=>n+(answers[i]===x.correctAnswer?1:0),0);return <div><div className="page-title"><span className="eyebrow">RESULT</span><h1>Quiz completed 🎉</h1><p>{quiz.title||"Your quiz"} performance.</p></div><div className="result-card"><div className="result-score"><strong>{score}/{questions.length}</strong><span>correct answers</span></div><div className="result-list">{questions.map((x,i)=><div className={`result-row ${answers[i]===x.correctAnswer?"correct":"wrong"}`} key={i}><CheckCircle2 size={18}/><span>Q{i+1}: {answers[i]===x.correctAnswer?"Correct":"Review this question"}</span></div>)}</div><button className="secondary-btn" onClick={()=>{setQuiz(null);setCurrent(0)}}><RotateCcw size={16}/> Create another</button></div></div>}
 return <div><div className="page-title"><span className="eyebrow">SMART ASSESSMENT</span><h1>Quiz Generator</h1><p>Create an AI-generated quiz and test your understanding.</p></div>
 <div className="quiz-layout"><div className="panel generator"><div className="panel-head"><div><h3><Sparkles size={18}/> Generate a quiz</h3><p>Choose the topic, level and number of questions.</p></div></div>{error&&<div className="alert error">{error}</div>}<label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}><option>Computer Science</option><option>Mathematics</option><option>Science</option><option>English</option><option>General Knowledge</option></select></label><label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} /></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label>Questions<select value={count} onChange={e=>setCount(Number(e.target.value))}><option value="5">5</option><option value="10">10</option><option value="15">15</option></select></label><button className="primary-btn full" onClick={generate} disabled={loading||!topic.trim()}><Brain size={17}/>{loading?"Generating...":"Generate Quiz"}</button></div>
 {q?<div className="panel quiz-card"><div className="quiz-progress"><span>Question {current+1} of {questions.length}</span><div><i style={{width:`${((current+1)/questions.length)*100}%`}}/></div></div><h2>{q.question}</h2><div className="options">{q.options.map((o,i)=><button className={answers[current]===i?"selected":""} key={i} onClick={()=>setAnswers(a=>({...a,[current]:i}))}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div><div className="quiz-nav"><button className="secondary-btn" disabled={current===0} onClick={()=>setCurrent(c=>c-1)}><ChevronLeft size={17}/> Previous</button><button className="primary-btn" onClick={()=>setCurrent(c=>c+1)}>{current===questions.length-1?"Finish":"Next"} <ChevronRight size={17}/></button></div></div>:<div className="panel quiz-placeholder"><Brain size={45}/><h3>Your generated quiz appears here</h3><p>Generate a quiz to start testing your knowledge.</p></div>}</div></div>
}