import { FormEvent, useEffect, useState } from "react";
import { CalendarDays, Check, Plus, Trash2, Target } from "lucide-react";

type Task={id:number;title:string;date:string;minutes:number;done:boolean};
export default function StudyPlanner(){
 const [tasks,setTasks]=useState<Task[]>(()=>JSON.parse(localStorage.getItem("edumind-tasks")||"[]")); const [title,setTitle]=useState(""); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [minutes,setMinutes]=useState(60);
 useEffect(()=>localStorage.setItem("edumind-tasks",JSON.stringify(tasks)),[tasks]);
 function add(e:FormEvent){e.preventDefault();if(!title.trim())return;setTasks(t=>[...t,{id:Date.now(),title:title.trim(),date,minutes,done:false}]);setTitle("");}
 const done=tasks.filter(t=>t.done).length; const total=tasks.reduce((n,t)=>n+t.minutes,0);
 return <div><div className="page-title"><span className="eyebrow">PERSONAL PLAN</span><h1>Study Planner</h1><p>Plan focused sessions and build a consistent learning habit.</p></div><div className="planner-grid"><div className="panel"><div className="panel-head"><div><h3>Create study session</h3><p>Add tasks for your day.</p></div><CalendarDays/></div><form onSubmit={add} className="planner-form"><label>What will you study?<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Practice binary trees"/></label><div className="two-col"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Minutes<input type="number" min={15} step={15} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label></div><button className="primary-btn"><Plus size={16}/> Add session</button></form></div><div className="panel planner-summary"><div className="summary-icon"><Target/></div><strong>{done}/{tasks.length||0}</strong><span>sessions completed</span><div className="summary-stat"><b>{Math.round(total/60)}h</b><small>planned study time</small></div></div></div><div className="panel"><div className="panel-head"><div><h3>Your sessions</h3><p>Tick off each task when you finish it.</p></div></div>{tasks.length?tasks.sort((a,b)=>a.date.localeCompare(b.date)).map(t=><div className={`task-row ${t.done?"done":""}`} key={t.id}><button className="check-btn" onClick={()=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,done:!x.done}:x))}>{t.done&&<Check size={15}/>}</button><div><b>{t.title}</b><small>{t.date} · {t.minutes} minutes</small></div><button className="delete-btn" onClick={()=>setTasks(ts=>ts.filter(x=>x.id!==t.id))}><Trash2 size={17}/></button></div>):<div className="empty"><CalendarDays size={28}/><b>No sessions yet</b><span>Create your first study session above.</span></div>}</div></div>
}